### ISSUE TITLE
CODE: Implement edit to replace quick replies with html

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#1]
The RapidPro-Wechat integration is not fully developed and quick replies are not supported. However WeChat supports html so as a way around it, we can add a feature to the code for handling quick replies so that:
1. quick replies are always removed from every node
2. quick replies are added back into the message text embedded into html (see format below)
3. wait for response nodes are not edited because clicking on the quick reply in html sends the message

---------------------
<a href=""weixin://bizmsgmenu?msgmenucontent=The parameters filled in here represent what the user is sending.&msgmenuid=projectid"">The parameters filled in here represent what the link displays.</a>"

video demonstration:
https://drive.google.com/file/d/1VGISDf4p0iFSkCHclD-yUxM-7IxEalkI/view?usp=sharing

**Comment by edmoss345** [comment]
Believe the above PR gives the desired functionality but need to do some further testing

**Comment by edmoss345** [comment]
Have tested the new functions as part of https://github.com/IDEMSInternational/idems_translation/pull/56, and the code is doing what I expect, but need to confirm that this is what is required. Below are some screenshots of what happens to the flow in RapidPro, I can't easily test these in WeChat, but could we maybe share this issue with the China team to confirm this is expected behaviour? There are also JSON test files added as part of this PR which are example before and after results, perhaps we could share theses with the China team for them to verify that they are functional on WeChat, would appreciate your thoughts @fagiothree 

Before change
![image](https://github.com/IDEMSInternational/parenttext-china/assets/69303397/bdeeb802-e52a-4da5-b650-13547ae3f02b)

After change
![image](https://github.com/IDEMSInternational/parenttext-china/assets/69303397/e8e79dab-ba3a-42ba-9cfe-97d0f58f789d)

**Comment by fagiothree** [comment]
Sent email to Zuyi and Wenhao to ask for help reviewing the html expression

**Comment by edmoss345** [comment]
After feedback from China team, have made some changes and retested in WeChat and everything seems to be working as expected. Will make some associated PRs to get this into the pipeline

**Comment by edmoss345** [comment]
Update to china repo PR https://github.com/IDEMSInternational/parenttext-china/pull/30

Update to pipeline repo PR https://github.com/IDEMSInternational/parenttext-pipeline/pull/72
