### ISSUE TITLE
TEMPLATE: Onboarding - Order of questions for caregiver name

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#4]
Parents should be asked “What is Your Last Name (family name)?” first, followed by “What is your first name?”

**Comment by edmoss345** [comment]
Template to be modified

https://docs.google.com/spreadsheets/d/12ddvTz_ZfC-9-b0yxjVrSzczciUUE3GosLUFeOLIv9I/edit#gid=1850106898

**Comment by edmoss345** [comment]
Have added an 'onboarding data' sheet to the CN localised data lists and flows and swapped the order of the two rows below, @fagiothree I think this means this issue is closed?


https://docs.google.com/spreadsheets/d/1CoYl7lpd6w2xdZzE-Crt-pZT9M5dTHYFm9sWEcX5QAs/edit#gid=365011271


![Image](https://github.com/IDEMSInternational/parenttext-china/assets/69303397/ea0f5a24-30c6-43cc-a4ea-4867735cfa68)
